#!/bin/sh
# Emit a Homebrew formula that installs the released source tree.
#
#   generate-formula.sh <version> <owner/repo> <dir-with-release-artifacts>
#
# The artifact directory must hold the .sha256 file packaging/archive.sh writes
# beside the tarball. Run after the release is published: publish-homebrew-
# formula.yml downloads that checksum from the release itself, so the hash in
# the formula is of the file users actually fetch.
set -eu

if [ "$#" -ne 3 ]; then
    echo "usage: generate-formula.sh <version> <owner/repo> <artifact-dir>" >&2
    exit 1
fi

version="$1"
repo="$2"
artifacts="$3"
base="https://github.com/${repo}/releases/download/v${version}"

# Read the checksum up front: a command substitution inside the heredoc below
# cannot abort this script, so a missing file there would silently yield a
# formula with an empty sha256.
checksum_file="${artifacts}/claude-slack-bridge-${version}.tar.gz.sha256"
if [ ! -s "$checksum_file" ]; then
    echo "missing or empty checksum: $checksum_file" >&2
    exit 1
fi
# the file holds "<hash> *<name>" — take only the hash
sha256="$(awk '{print $1; exit}' "$checksum_file")"

# The template is a quoted heredoc: nothing in it is expanded, so backticks in
# the caveats cannot run as commands and $VAR cannot leak the builder's
# environment into a published formula. Values are substituted afterwards.
cat <<'FORMULA' | sed \
    -e "s|@VERSION@|${version}|g" \
    -e "s|@REPO@|${repo}|g" \
    -e "s|@BASE@|${base}|g" \
    -e "s|@SHA256@|${sha256}|g"
# Generated by packaging/homebrew/generate-formula.sh — do not edit by hand.
class ClaudeSlackBridge < Formula
  desc "Two-way bridge between Claude Code and Slack, over Socket Mode"
  homepage "https://github.com/@REPO@"
  url "@BASE@/claude-slack-bridge-@VERSION@.tar.gz"
  version "@VERSION@"
  sha256 "@SHA256@"
  license "MIT"

  # The dev track: `brew install --HEAD` installs the tip of main instead of a
  # release. Nothing is compiled either way — the daemon itself is built by
  # `docker compose up --build` on first start — so this needs no extra
  # dependency, only a different source. A one-liner rather than a `head do`
  # block, which brew style rejects as redundant when it holds nothing but a
  # url.
  head "https://github.com/@REPO@.git", branch: "main"

  # Docker is deliberately not a dependency. `depends_on cask:` is discouraged
  # outside homebrew/core and would be wrong anyway: OrbStack, Colima and
  # Docker Desktop all satisfy this, and the formula has no business picking.
  # The wrapper waits for whichever one is installed to come up.

  def install
    # The whole tree, because the release IS the build context: `docker compose
    # up --build` runs against these files. Dir["*"] skips dotfiles, so the one
    # dot-directory that belongs in a release is named.
    libexec.install Dir["*"]
    libexec.install ".claude-plugin" if File.exist?(".claude-plugin")

    # The wrapper cannot find these itself: libexec sits four levels down
    # inside the Cellar, and counting ".." back out would break the day
    # Homebrew changes that layout.
    inreplace libexec/"bin/claude-slack-bridge" do |s|
      s.gsub! "@LIBEXEC@", libexec
      s.gsub! "@ETC@", etc/"claude-slack-bridge"
    end
    bin.install_symlink libexec/"bin/claude-slack-bridge"

    # No config is created, here or in post_install. It holds two Slack tokens,
    # so it is the user's to write — and a formula that never touches it cannot
    # overwrite it on upgrade. The template it is copied from stays in libexec,
    # where every upgrade refreshes it; a copy under etc would be frozen at
    # whatever the first install shipped, because Homebrew preserves etc.
  end

  # `brew services start claude-slack-bridge` installs this as a launchd user
  # agent on macOS and a systemd user unit on Linux. The wrapper runs compose in
  # the foreground so there is a process to supervise, and switches the
  # container's own restart policy off so launchd is the only thing restarting
  # it.
  service do
    run [opt_bin/"claude-slack-bridge", "start"]
    keep_alive true
    log_path var/"log/claude-slack-bridge.log"
    error_log_path var/"log/claude-slack-bridge.log"
    environment_variables PATH: std_service_path_env
  end

  def caveats
    <<~EOS
      This runs the daemon in a container, so install a Docker engine first —
      any of them:

        brew install --cask orbstack        # lightest
        brew install --cask docker

      Then write your config. It is not created for you, because it holds your
      Slack tokens:

        mkdir -p ~/.config/claude-slack-bridge
        cp #{opt_libexec}/config.env.default ~/.config/claude-slack-bridge/config.env
        chmod 600 ~/.config/claude-slack-bridge/config.env

      Fill in SLACK_BOT_TOKEN and SLACK_APP_TOKEN (see docs/slack-setup.md in
      #{opt_libexec}/docs) and point PROJECTS_DIR at the parent directory of your
      projects. Read the access-control section while you are in there: the
      Slack side can run Claude against your files, and the template ships
      denying everyone until you add your own Slack user ID.

      Then start it. The first start builds the image, which takes a few
      minutes; later ones are near-instant:

        brew services start claude-slack-bridge
        claude-slack-bridge logs

      The channel to project mapping is ~/.config/claude-slack-bridge/projects.json,
      created empty on first start. After editing it, apply it live — no
      restart, no dropped Slack connection, no killed runs:

        claude-slack-bridge reload

      Homebrew does not restart services on upgrade, so after `brew upgrade` the
      old container keeps serving until you do:

        brew services restart claude-slack-bridge

      Do NOT use `sudo brew services`: the container mounts your ~/.claude, and
      a system daemon has the wrong home directory for that.
    EOS
  end

  test do
    # The wrapper is useless if the install-time substitution did not happen: it
    # would fall back to guessing a path from $0 and, finding no compose file,
    # fail at first start inside launchd's log where nobody is looking.
    wrapper = (libexec/"bin/claude-slack-bridge").read
    refute_match "@LIBEXEC@", wrapper
    refute_match "@ETC@", wrapper
    assert_match libexec.to_s, wrapper

    # The tarball has to carry the build context, not just the wrapper.
    assert_path_exists libexec/"docker-compose.yml"
    assert_path_exists libexec/"Dockerfile"
    assert_path_exists libexec/"config.env.default"
    assert_path_exists libexec/"src/main.py"

    # Runs under /bin/sh in launchd, where a syntax error is a restart loop.
    system "/bin/sh", "-n", bin/"claude-slack-bridge"
  end
end
FORMULA
